routes/web.php
<?php

use App\Http\Controllers\CommentController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();


// GET ROUTES

// Welcome page
Route::get('/', [PostController::class, 'index'])->name('welcome');

// User homepage
Route::get('/home', [HomeController::class, 'index'])->name('home');

// Single post by logged User (owner)
Route::get('/home-show-single-post/{id}', [HomeController::class, 'showSingleUserPost'])->name('singleUserPost');

// Edit user profile
Route::get('/edit-user-profile', [HomeController::class, 'editUserProfile'])->name('editUserProfile');



// POST ROUTES

// Add user image
Route::post('/home-save-img', [HomeController::class, 'saveImg'])->name('saveImg');

// Create comment on post by logged user
Route::post('/comment/{id}', [CommentController::class, 'createComment'])->name('createComment');


// DELETE ROUTES

// Delete comment by post owner or comment owner
Route::delete('/comment-delete/{id}', [CommentController::class, 'destroy'])->name('commentDelete');

// Delete image on user profile
Route::delete('/home-delete-img', [HomeController::class, 'deleteImg'])->name('deleteImg');

// Delete user profile by user
Route::delete('/home-delete-user/{id}', [HomeController::class, 'deleteUser'])->name('deleteUser');


// RESOURCEFUL ROUTE
Route::resource('post', PostController::class);

resources/views/createBlogForm.blade.php
@extends('layouts.app')
@section('title')
    Create new post
@endsection
@section('content')

{{-- Main Container Start --}}
<div class="container">
    <h2 class="text-center mt-5">Lets create something amaizing</h2><br>

    <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <label for="description">Required <span class="text-danger">*</span></label>
        <input type="text" name="description" class="form-control" placeholder="description"><br>
        <label for="body">Required <span class="text-danger">*</span></label>
        <textarea class="form-control" name="body" id="editor"  cols="30" rows="10" placeholder="Write your post"></textarea>
        <br>
        <label class="ml-2" for="image1">Add image 1 (Optional)</label>
        <input type="file" name="image1" class="form-control"><br>

        <label class="ml-2" for="image1">Add image 2 (Optional)</label>
        <input type="file" name="image2" class="form-control"><br>

        <label class="ml-2" for="image1">Add image 3 (Optional)</label>
        <input type="file" name="image3" class="form-control"><br>

        <select name="category" class="form-control">
            @foreach ($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>
        <br>
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
</div>
{{-- Main Container End --}}

@endsection

{{-- Text Editor Start --}}
@section('editor-scripts')

<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

@endsection
{{-- Text Editor End --}}

resources/views/editPost.blade.php
@extends('layouts.app')
@section('title')
    Edit post
@endsection
@section('content')

{{-- Main Container Start --}}
<div class="container">
    <h2 class="text-center mt-5">Edit post</h2><br>

    <form action="{{ route('post.update', ['post'=>$post->id]) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <input class="form-control" type="text" name="description" value="{{ $post->description }}"><br>
        <textarea class="form-control" name="body" id="editor"  cols="30" rows="10">
          {!!$post->body!!}
        </textarea>
        <br>
        <label class="ml-2" for="image1">Add image 1 (Optional)</label>
        <input type="file" name="image1" class="form-control post-image1"><br>

        <label class="ml-2" for="image2">Add image 2 (Optional)</label>
        <input type="file" name="image2" class="form-control"><br>

        <label class="ml-2" for="image3">Add image 3  (Optional)</label>
        <input type="file" name="image3" class="form-control"><br>
        <select name="category" class="form-control">
            <option value="{{ $post->category->id }}">{{ $post->category->name }}</option>

            @foreach ($categories as $category)
                <option value="{{ $category->id }}">{{ $category->name }}</option>
            @endforeach
        </select>
        <br>
        <button class="btn btn-success" type="submit">Save edited post</button>
    </form>
</div>
{{-- Main Container End --}}
@endsection


{{-- Text Editor Start --}}
@section('editor-scripts')

<script>
    ClassicEditor
        .create( document.querySelector( '#editor' ) )
        .catch( error => {
            console.error( error );
        } );
</script>

@endsection
{{-- Text Editor End --}}

resources/views/editUserProfile.blade.php
@extends('layouts.app')
@section('title')
    {{ $user->name }} homepage
@endsection
@section('content')
<div class="container-fluid bg-secondary">
    <div class="row">
        <div class="col-md-2 offset-md-5 text-center">
            <h2 class="mt-5 text-white user_name">{{ $user->name }}</h2>
            <p class="text-white">Memaber since: {{ $user->created_at->format('M. d. Y') }}</p>
        </div>
        <div class="col-md-3 offset-md-5">
            <img
            @if (isset(Auth::user()->user_image))
               src="{{ asset('/images/user_image/'.Auth::user()->user_image) }}"
            @else

              src="{{ asset('/images/user_image/noimage.jpg') }}"

            @endif

            class="img-fluid p-3 user-image mt-1 rounded-circle" style="width:300px">
        </div>

    </div>
    <div class="row">

        <div class="col-md-4 offset-md-5 mb-3 px-5">
            <a href="{{url('/home') }}" class="btn btn-primary rounded-pill ml-3">Back to my profile</a>
        </div>
        <div class="col-md-2 offset-md-1">
            <form action="{{ route('deleteUser', ['id'=>Auth::user()->id]) }}" method="post">
                @csrf
                @method('delete')
            <button type="submit" class="btn btn-danger rounded-pill"
            onclick="return confirm('Are you sure you want to delete your profile');">Delete profile</button>
            </form>
        </div>

    </div>

</div>


<div class="container content">
    <div class="row">
        <div class="col-md-10 offset-md-1 ml-3 mt-5">
            <h2 class="ml-3">Name: {{ $user->name }}</h2>
            <h2 class="ml-3">Last Name: {{ $user->last_name }}</h2>
            <h3 class="ml-3">Email: {{ $user->email }}</h3>

            <div class="form-add-userImg mt-5">
                <form action="{{ route('saveImg')}}" method="post" enctype="multipart/form-data">
                    @csrf
                        <input  type="file" id="user_image" name="user_image" class="ml-3 input-img"><br>
                        <button class="btn btn-primary ml-3 mt-1 px-4 btn-addImg" type="submit">Add profile image</button>
                </form>
            </div>

            <div class="form-delete-UserImg mt-3">
               <form action="{{ route('deleteImg')}}" method="post">
                   @csrf
                   @method('delete')
                   <button class="btn btn-danger ml-3 px-4 btn-deleteImg" type="submit"
                   onclick="return confirm('Are you sure you want to delete your profile image');">Delete profile image</button>
               </form>
            </div>



        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('title')
    {{ $user->name }} homepage
@endsection
@section('content')
{{-- Container1  Start --}}
<div class="container-fluid bg-secondary">
    <div class="row">
        <div class="col-md-2 pl-5 offset-md-5 text-center">
            <h2 class="mt-5 text-white user_name">{{ $user->name }}</h2>
            <p class="text-white">Memaber since: {{ $user->created_at->format('M. d. Y') }}</p>
        </div>
        <div class="col-md-3 offset-md-5">
            <img
            @if (isset(Auth::user()->user_image))
               src="{{ asset('/images/user_image/'.Auth::user()->user_image) }}"
            @else

              src="{{ asset('/images/user_image/noimage.jpg') }}"

            @endif

            class="img-fluid p-3 user-image mt-1 rounded-circle">
        </div>
        <div class="col-md-5 offset-md-5 mb-3">

               <a href="{{ route('post.create') }}" class="btn btn-primary  rounded-pill ml-2">Create new Post</a>
               <a href="{{ route('editUserProfile') }}" class="btn btn-primary  rounded-pill">Edit Profile</a>
        </div>
    </div>

</div>
{{-- Conatiner1 End --}}
{{-- Conatiner2 Start --}}
<div class="container-fluid">
    <div class="row">
        <div class="col home-title">
            @if ($posts->count() == 0)
               <h2 class="mt-5 mb-5 text-center text-muted">Wow, that's a very clean portfolio!</h2>
            @else
              <h2 class="mt-5 mb-5 text-center text-muted">All your posts</h2>
            @endif
        </div>
    </div>
</div>
{{-- Conatiner2 End --}}


{{-- Conatiner3 Start --}}
<div class="container content justify-content-center">


        <div class="row">

            {{-- All User Posts --}}
            @foreach ($posts as $post)
            <div class="col-md-4  mt-5 pt-5">
                <div class="card text-center ">
                    <div class="card-header bg-dark text-light">
                       <p class="float-left mt-2">Author: {{ $post->user->name }} </p>
                       <p class="float-right mt-2">Views: {{ $post->views }} </p>
                    </div>
                    <div class="card-body">
                      <a class="text-muted" href="{{ route('singleUserPost', ['id'=>$post->id]) }}">
                        <h5 class="card-title">{{ $post->description }}</h5>
                        @if (isset($post->image1))
                            <img class="img-fluid card-img" src="/images/post_images/{{ $post->image1 }}" class="card-img">
                        @elseif(isset($post->image2))
                            <img class="img-fluid card-img" src="/images/post_images/{{ $post->image2 }}" class="card-img">
                        @elseif(isset($post->image3))
                            <img class="img-fluid card-img" src="/images/post_images/{{ $post->image3 }}" class="card-img">
                        @else
                            <img class="img-fluid card-img" src="/images/post_images/noimage.jpg">
                        @endif
                      </a>
                    </div>
                    <div class="card-footer text-muted bg-dark text-white">
                      <p class="float-left text-white mt-2">Created: {{ $post->created_at->format('d.m.Y') }}</p>
                      <p class="float-right text-white mt-2">Updated: {{ $post->updated_at->format('d.m.Y') }}</p>
                    </div>
                </div>
            </div>
           @endforeach
           {{-- All User Posts End --}}
        </div>




</div>
{{-- Conatiner3 End --}}


@endsection

resources/views/showSingleUserPost.blade.php
@extends('layouts.app')
@section('title')
    Show single post
@endsection
@section('content')
    {{-- Container Start --}}
    <div class="container-fluid content">
        <div class="row">
             <div class="col-md-8 offset-md-2 mt-5">
                    <div class="card">
                        <div class="container">

                            <div class="row mt-3">
                                <div class="col-md-4 ">
                                    @if (isset($post->image1))
                                    <img class="img-fluid card-img " src="/images/post_images/{{ $post->image1 }}">
                                    @else
                                    <img class="img-fluid card-img p-2" src="/images/post_images/noimage.jpg">
                                    @endif
                                </div>
                                <div class="col-md-4">
                                    @if (isset($post->image2))
                                    <img class="img-fluid card-img " src="/images/post_images/{{ $post->image2 }}">
                                    @else
                                    <img class="img-fluid card-img " src="/images/post_images/noimage.jpg">
                                    @endif
                                </div>
                                <div class="col-md-4">
                                    @if (isset($post->image3))
                                    <img class="img-fluid card-img " src="/images/post_images/{{ $post->image3 }}">
                                    @else
                                    <img class="img-fluid card-img p-2" src="/images/post_images/noimage.jpg">
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-10 offset-md-1 mb-5">
                                <div class="container-fluid mt-5">
                                    <h2 class="text-center mt-5"><strong>{{ $post->description }}</strong></h2>
                                    <p>{!!$post->body!!}</p>
                                </div>

                            </div>

                        </div>
                    </div><br>
                        {{-- Edit Post Start --}}
                        <a href="{{ route('post.edit', ['post'=>$post->id]) }}" class="btn btn-secondary float-left">Edit Post</a>
                        {{-- Edit Post End --}}

                        {{-- Delete Post Form Start --}}
                        <form action="{{ route('post.destroy', ['post'=>$post->id]) }}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-secondary float-right">Delete post</button>
                        </form>
                        {{-- Delete Post Form End --}}
                        <br><br>
             </div>
        </div>
    </div>
    {{-- Container End --}}
@endsection

resources/views/singlePostView.blade.php
@extends('layouts.app')
@section('title')
    {{ $post->description }}
@endsection
@section('content')
    {{-- Main Container --}}
    <div class="container content">
        <div class="row">
            <div class="col-md-10 offset-md-1 mt-5">
                  <div class="card p-5 ">
                      <div>
                            <p class="float-left">Author: {{ $post->user->name }}
                            <span class="ml-3">
                            <img class="img-fluid"
                                @if (isset($user->user_image))
                                    src="/images/user_image/{{ $user->user_image }}"
                                @else
                                    src="/images/user_image/noimage.jpg"
                                @endif
                                style="width:70px; border-radius:50%; height:70px">
                            </span></p>
                            <p class="float-right mt-3">Updated: {{ $post->updated_at->format('d.m.Y') }}</p>
                      </div>

                      <div class="row mt-5">
                          <div class="col-md-4 mt-2">
                                @if (isset($post->image1))
                                <img class="img-fluid card-img" src="/images/post_images/{{ $post->image1 }}">
                                @else
                                    <img class="img-fluid card-img" src="/images/post_images/noimage.jpg">
                                @endif

                            </div>

                            <div class="col-md-4 mt-2">
                                @if (isset($post->image2))
                                <img class="img-fluid card-img" src="/images/post_images/{{ $post->image2 }}">
                                @else
                                    <img class="img-fluid card-img" src="/images/post_images/noimage.jpg">
                                @endif

                            </div>

                            <div class="col-md-4 mt-2">
                                @if (isset($post->image3))
                                <img class="img-fluid card-img" src="/images/post_images/{{ $post->image3 }}">
                                @else
                                    <img class="img-fluid card-img" src="/images/post_images/noimage.jpg">
                                @endif

                            </div>
                        </div>
                      <div class="container-fluid mt-5">
                        <h2 class="text-center mt-5"><strong>{!! $post->description !!}</strong></h2>
                        <p class="mt-5 p-3">{!! $post->body !!}</p>
                      </div>

                  </div><br>


            </div>
        </div>
          {{-- Comments start --}}
         <div class="row">
             <div class="col-md-10 offset-md-1">

                <h2>Comments</h2>

             </div>
            <div class="col-md-10 offset-md-1">




                @foreach( $comments as $comment)
                @if ($comment->post_id == $post->id)

                    <div class="card mt-2">
                        <div class="card">
                            <div class="row">

                                <div class="col-md-6">
                                    <p class="mt-2 ml-2"><b>{{ $comment->user->name }}</b>
                                        <span class="ml-5 pl-5 float-right">Created: {{ $comment->created_at->format('d.m.Y') }}</span>
                                    </p>
                                </div>

                                <div class="col-md-6">
                                    @if (auth()->check() && Auth::user()->id == $comment->sender_id ||auth()->check() && Auth::user()->id == $post->user_id)
                                    <form action="{{ route('commentDelete', ['id'=>$comment->id]) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn float-right" >
                                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="comment-delete-btn bi bi-x-square-fill mt-1" viewBox="0 0 16 16">
                                                <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1
                                                .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708z"/>
                                              </svg>
                                        </button>
                                    </form>
                                    @endif

                                </div>

                            </div>


                        </div>
                        <div>
                            <p class="p-2"><b>{{ $comment->body }}</b></p>

                        </div>

                    </div>
                @endif

                @endforeach

            </div>
         </div>

         {{-- Comments End --}}

        <br>
        {{-- Comment Form Start--}}
        <div class="row">
            <div class="col-md-10 offset-md-1">
                @if (Auth::user())
                <form action="{{ route('createComment', ['id' =>$post->id]) }}" method="post">
                    @csrf
                    <input type="text" name="body" class="form-control" placeholder="Write your comment here"><br>
                    <button class="btn btn-primary" type="submit">Add Comment</button>

                </form>
                @endif
                <br><br>
            </div>
        </div>
        {{-- Comment Form End --}}
    </div>
    {{-- Main Container End --}}
@endsection